name: Release Builds
on:
  push:
    tags:
      - v3*
      - v4*
jobs:
  package_build:
    if: github.repository == 'kafka-ops/julie'
    name: Build rpm/deb packages (using maven)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Import private GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Import public GPG Key
        run: rpm --import release/keys/public.key
      - name: Set up the JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: "temurin"
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn -Dgpg.passphrase="$GPG_PASSPHRASE" --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Build the rpm
        run: mvn rpm:rpm
      - name: Sign rpm
        run: |
          rpm --define "_gpg_name ${{ steps.import_gpg.outputs.keyid }}" --addsign target/rpm/julie-ops/RPMS/noarch/*.rpm
          rpm --checksig target/rpm/julie-ops/RPMS/noarch/*.rpm
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_NAME: ${{ steps.import_gpg.outputs.email }}
      - name: Sign deb
        run: |
          sudo apt-get install dpkg-sig -y
          dpkg-sig -k ${{ steps.import_gpg.outputs.keyid }} --sign builder $FILE target/*.deb
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_NAME: ${{ steps.import_gpg.outputs.email }}
      - uses: actions/upload-artifact@v2
        with:
          name: RPM package
          path: target/rpm/julie-ops/RPMS/noarch/*.rpm
      - uses: actions/upload-artifact@v2
        with:
          name: DEB package
          path: target/*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: FAT jar
          path: target/julie-ops.jar
